listOfVariablesInOldModel = [{'weight'}; {'speed'}; {'size'}; {'yaw'}; {'pitch'}; {'roll'}; {'width'}; ...
    {'wheelTorque'}; {'thrust'}; {'acceleration'}; {'lateralPosition'}; {'horizontalPosition'}; ...
    {'longitudinalPosition'}];

listOfVariablesInNewModel = [{'x'}; {'weight'}; {'speed'}; {'y'}; {'size'}; {'yaw'}; {'pitch'}; {'roll'}; ...
    {'width'}; {'wheelTorque'}; {'thrust'}; {'acceleration'}; {'z'}];

[newElements removedElements] = newOld(listOfVariablesInOldModel, listOfVariablesInNewModel)