listOfVarOldModel = [{'weight'}; {'speed'}; {'size'}; {'yaw'}; {'pitch'}; {'roll'}; ...
    {'width'}; {'wheelTorque'}; {'thrust'}; {'acceleration'}; {'lateralPosition'}; ...
    {'horizontalPosition'}; {'longitudinalPosition'}];

listOfVarNewModel = [{'x'}; {'weight'}; {'speed'}; {'y'}; {'size'}; {'yaw'}; {'pitch'}; ...
    {'roll'}; {'width'}; {'wheelTorque'}; {'thrust'}; {'acceleration'}; {'z'}];

[newElements removedElements] = newOld(listOfVarOldModel, listOfVarNewModel)
